import fs from 'node:fs';
const sites=JSON.parse(fs.readFileSync(new URL('./sites.json',import.meta.url)));
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const page=s=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(s.name)}</title><link rel="stylesheet" href="styles.css"></head><body><div class="shell"><nav class="nav"><a class="brand" href="index.html">FINITE/10</a><span class="pill">10,000 total tiles</span></nav><section class="hero"><div><div class="eyebrow">${escape(s.eyebrow)}</div><h1>${escape(s.name)}</h1><p class="lede">${escape(s.description)}</p></div><div class="stats"><div class="stat"><strong>£${s.price}</strong><span>prototype tile price</span></div><div class="stat"><strong>9,150</strong><span>tiles available</span></div><div class="stat"><strong>${escape(s.buyer)}</strong><span>ideal buyer</span></div><div class="stat"><strong>${escape(s.returnLoop)}</strong><span>return loop</span></div></div></section><main class="grid-wrap"><div class="canvas-card"><canvas aria-label="Interactive finite inventory grid"></canvas></div><aside class="panel"><div class="eyebrow">Selected inventory</div><p class="selection">Choose a tile</p><h2>${escape(s.unit)}</h2><p class="note">Click any dark tile. Bright tiles simulate claimed inventory. This prototype creates a local reservation only and takes no payment.</p><button class="cta" disabled>Reserve prototype tile</button></aside></main></div><script>window.SITE_CONFIG=${JSON.stringify(s)}</script><script src="app.js"></script></body></html>`;
for(const site of sites)fs.writeFileSync(new URL(`./${site.slug}.html`,import.meta.url),page(site));
const cards=sites.map(s=>`<a class="card" style="--accent:${s.accent}" href="${s.slug}.html"><div class="eyebrow">${escape(s.eyebrow)}</div><h2>${escape(s.name)}</h2><p>${escape(s.description)}</p><b>Open prototype →</b></a>`).join('');
fs.writeFileSync(new URL('./index.html',import.meta.url),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FINITE/10</title><link rel="stylesheet" href="styles.css"></head><body><div class="shell"><nav class="nav"><span class="brand">FINITE/10</span><span class="pill">2026 digital real-estate lab</span></nav><section class="hero"><div><div class="eyebrow">Ten scarce internet canvases</div><h1>The homepage idea, rebuilt for 2026.</h1><p class="lede">Ten independently deployable experiments. One shared engine. No domains bought and no payment activated yet.</p></div></section><main class="catalog">${cards}</main></div></body></html>`);
console.log(`generated ${sites.length} storefronts`);

